apply plugin: 'com.android.application'
//apply plugin: 'com.google.gms.google-services'
//apply plugin: 'com.google.firebase.crashlytics'

android {
    signingConfigs {
        release {
            storeFile file("$project.rootDir/keystores/CanZeKeyStore.jks")
            storePassword 'canze4us!'
            keyAlias = 'canze-upload'
            keyPassword 'canze4us!'
        }
    }
    compileSdk 36

    defaultConfig {
        applicationId "cz.mtrakal.canze"
        minSdkVersion 29
        versionName '1.68'
        versionCode 103
    }
    buildTypes {
        release {
            //  minifyEnabled false
            //  minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        //debug {
        //    minifyEnabled true
        //    proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        //}
    }
    flavorDimensions = ["edition"]
    productFlavors {
        playstore {
            dimension "edition"
        }
        fdroid {
            dimension "edition"
        }
    }
    defaultConfig {

        targetSdk 36
        buildConfigField "long", "TIMESTAMP", System.currentTimeMillis() + "L"
        buildConfigField "String", "BRANCH", "\"" + "debug" + "\""
        signingConfig signingConfigs.release
    }
    namespace 'lu.fisch.canze'
    lint {
        abortOnError false
        checkReleaseBuilds false
        disable 'TypographyFractions'
    }
    buildFeatures {
        buildConfig true
    }
}

//static def getGitRevParseInfo() {
//    def cmd = "git rev-parse --abbrev-ref HEAD"
//    def proc = cmd.execute()
//    proc.text.trim()
//}

dependencies {
    // BoM for the Firebase platform
    playstoreImplementation libs.firebase.bom

    // Dependencies for the desired Firebase products without specifying versions
    playstoreImplementation libs.firebase.analytics
    playstoreImplementation libs.firebase.crashlytics

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation libs.androidx.legacy.support.v4
    implementation libs.androidx.appcompat
    implementation libs.toastcompat
    implementation libs.gson
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.preference

    implementation libs.firebase.crashlytics.ktx
    implementation libs.firebase.analytics.ktx

    //implementation 'com.firebase:firebase-client-android:2.5.0'

    implementation libs.usb.serial.for1.android

    // Android Auto dependencies
    implementation libs.androidx.app
    implementation libs.androidx.app.projected
    testImplementation libs.androidx.app.testing
}
